services:
  # ---------------- Source Database ----------------

  source:
    image: postgres:16
    container_name: source_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: source_postgres
      POSTGRES_PASSWORD: sourcepostgres
      POSTGRES_DB: source

    ports:
      - "5437:5432"

    volumes:
      - source_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U source_postgres -d source"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - pipeline_network


  

  # ---------------- Data Initialization ----------------

  data_init:
    build:
      context: "./workers/data init"
      dockerfile: Dockerfile
  
    image: data_init:latest
    container_name: data_init
    restart: "no"
  
    profiles:
      - manual
  
    environment:
      SOURCE_DATABASE_URL: postgresql+psycopg2://source_postgres:sourcepostgres@source:5432/source
  
    depends_on:
      source:
        condition: service_healthy
  
    networks:
      - pipeline_network


  # ---------------- Airflow Database ----------------

  airflow_db:
    image: postgres:16
    container_name: airflow_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    volumes:
      - airflow_db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - pipeline_network


  # ---------------- Airflow Initialization ----------------

  airflow_init:
    build:
      context: ./airflow
      dockerfile: Dockerfile

    image: custom_airflow:latest
    container_name: airflow_init

    depends_on:
      airflow_db:
        condition: service_healthy

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

    entrypoint: /bin/bash

    command:
      - -c
      - |
        set -e

        airflow db migrate

        airflow users create \
          --username admin \
          --password admin \
          --firstname admin \
          --lastname admin \
          --role Admin \
          --email admin@example.com || true

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs

    networks:
      - pipeline_network


  # ---------------- Airflow Webserver ----------------

  airflow_webserver:
    image: custom_airflow:latest
    container_name: airflow_webserver
    restart: unless-stopped

    depends_on:
      airflow_init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

    ports:
      - "8080:8080"

    command: webserver

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - pipeline_network


  # ---------------- Airflow Scheduler ----------------

  airflow_scheduler:
    image: custom_airflow:latest
    container_name: airflow_scheduler
    restart: unless-stopped

    depends_on:
      airflow_init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

    command: scheduler

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - pipeline_network



  # ---------------- Spark Master ----------------

  spark_master:
    image: spark:4.1.2-scala2.13-java17-python3-ubuntu
    container_name: spark_master
    restart: unless-stopped

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master

    environment:
      SPARK_NO_DAEMONIZE: "true"
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: "7077"
      SPARK_MASTER_WEBUI_PORT: "8080"

    ports:
      # Spark cluster connection
      - "7077:7077"

      # Host port 8082 is used because Airflow already uses 8080
      - "8082:8080"

    networks:
      pipeline_network:
        aliases:
          - spark-master


  # ---------------- Spark Worker ----------------

  spark_worker:
    image: spark:4.1.2-scala2.13-java17-python3-ubuntu
    container_name: spark_worker
    restart: unless-stopped

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077

    environment:
      SPARK_NO_DAEMONIZE: "true"
      SPARK_WORKER_CORES: "4"
      SPARK_WORKER_MEMORY: "4g"
      SPARK_WORKER_WEBUI_PORT: "8081"

    ports:
      - "8083:8081"

    depends_on:
      - spark_master

    networks:
      - pipeline_network

  # ---------------- Spark Silver Jobs ----------------
  silver_job:
    build:
      context: "./spark/jobs/silver_jobs"
      dockerfile: Dockerfile

    image: silver_job:latest
    container_name: silver_job
    restart: "no"

    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      SOURCE_JDBC_URL: jdbc:postgresql://source:5432/source
      SOURCE_TABLE: raw.customer
      SOURCE_DB_USER: source_postgres
      SOURCE_DB_PASSWORD: sourcepostgres
      SOURCE_PARTITION_COLUMN: customer_id
      SOURCE_LOWER_BOUND: "1"
      SOURCE_UPPER_BOUND: "10000000"
      SOURCE_NUM_PARTITIONS: "8"

    depends_on:
      source:
        condition: service_healthy
      spark_master:
        condition: service_started
      spark_worker:
        condition: service_started

    networks:
      - pipeline_network

  # ---------------- Dagster ----------------

  dagster:
    build:
      context: ./dagster
      dockerfile: Dockerfile

    image: custom_dagster:latest
    container_name: dagster
    restart: unless-stopped

    working_dir: /opt/dagster/app

    environment:
      DAGSTER_HOME: /opt/dagster/home

    command:
      - dagster
      - dev
      - -f
      - /opt/dagster/app/dags/definitions.py
      - -h
      - 0.0.0.0
      - -p
      - "3000"

    ports:
      - "3000:3000"

    volumes:
      # Dagster job definitions
      - ./dagster/dags:/opt/dagster/app/dags

      # Persist Dagster run history
      - dagster_home:/opt/dagster/home

      # Allow Dagster to launch Docker containers
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      source:
        condition: service_healthy

    networks:
      - pipeline_network


# ---------------- Named Volumes ----------------

volumes:
  source_data:
  airflow_db_data:
  airflow_logs:
  dagster_home:
  spark_worker_data:


# ---------------- Docker Network ----------------

networks:
  pipeline_network:
    name: dagster-vs-airflow-network